management:
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  cloud:
    gateway:
      routes:
        - id: ccb-test
          uri: http://test-api.axzo.cn
          predicates:
            - Path=/ccb-test/batch/**
          filters:
            - RewritePath=/ccb-test/?(?<segment>.*), /meepo/api/pay/gateway/$\{segment}
        - id: ccb-pro
          uri: http://test-api.axzo.cn
          predicates:
            - Path=/ccb-pro/batch/**
          filters:
            - RewritePath=/ccb-pro/?(?<segment>.*), /meepo/api/pay/gateway/$\{segment}



reactor:
  netty:
    http:
      server:
        accessLogEnabled=true: