feign:
  client:
    url.ccb: https://api.virapi.com/vir_github256gbaa2a8b48/demo
    config:
      default:
        loggerLevel: FULL
        connectTimeout: 3300
        readTimeout: 4400
      ccb-pay:
        connectTimeout: 100
        readTimeout: 1000
logging.level.com.zxin.javaspring.cloud.feign.es.CatFeignClient: debug